/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as FormPlaygroundRouteImport } from './routes/form-playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LogoutSuccessRouteImport } from './routes/logout-success'
import { Route as Oauth2_callbackRouteImport } from './routes/oauth2_callback'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppModuleIdRouteImport } from './routes/_app.$moduleId'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppXcustomersRouteImport } from './routes/_app.xcustomers'
import { Route as AppModuleIdIndexRouteImport } from './routes/_app.$moduleId.index'
import { Route as AppModuleIdTable_nameRouteImport } from './routes/_app.$moduleId.$table_name'
import { Route as AppCrmHomeRouteImport } from './routes/_app.crm.home'
import { Route as AppXcustomersIdRouteImport } from './routes/_app.xcustomers.$id'
import { Route as AppXcustomersNewRouteImport } from './routes/_app.xcustomers.new'
import { Route as AppModuleIdTable_nameKeyRouteImport } from './routes/_app.$moduleId.$table_name.$key'
import { Route as AppCrmHomeDetailRouteImport } from './routes/_app.crm.home.detail'
import { Route as AppXcustomersIdEditRouteImport } from './routes/_app.xcustomers.$id.edit'
import { Route as AppModuleIdTable_nameKeyViewRouteImport } from './routes/_app.$moduleId.$table_name.$key.view'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const FormPlaygroundRoute = FormPlaygroundRouteImport.update({
  id: '/form-playground',
  path: '/form-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutSuccessRoute = LogoutSuccessRouteImport.update({
  id: '/logout-success',
  path: '/logout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2_callbackRoute = Oauth2_callbackRouteImport.update({
  id: '/oauth2_callback',
  path: '/oauth2_callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppXcustomersRoute = AppXcustomersRouteImport.update({
  id: '/xcustomers',
  path: '/xcustomers',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleIdIndexRoute = AppModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppModuleIdRoute,
} as any)
const AppModuleIdTable_nameRoute = AppModuleIdTable_nameRouteImport.update({
  id: '/$table_name',
  path: '/$table_name',
  getParentRoute: () => AppModuleIdRoute,
} as any)
const AppCrmHomeRoute = AppCrmHomeRouteImport.update({
  id: '/crm/home',
  path: '/crm/home',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.crm.home.lazy').then((d) => d.Route))
const AppXcustomersIdRoute = AppXcustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppXcustomersRoute,
} as any)
const AppXcustomersNewRoute = AppXcustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppXcustomersRoute,
} as any)
const AppModuleIdTable_nameKeyRoute =
  AppModuleIdTable_nameKeyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AppModuleIdTable_nameRoute,
  } as any).lazy(() =>
    import('./routes/_app.$moduleId.$table_name.$key.lazy').then(
      (d) => d.Route,
    ),
  )
const AppCrmHomeDetailRoute = AppCrmHomeDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => AppCrmHomeRoute,
} as any).lazy(() =>
  import('./routes/_app.crm.home.detail.lazy').then((d) => d.Route),
)
const AppXcustomersIdEditRoute = AppXcustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppXcustomersIdRoute,
} as any)
const AppModuleIdTable_nameKeyViewRoute =
  AppModuleIdTable_nameKeyViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AppModuleIdTable_nameKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logout-success': typeof LogoutSuccessRoute
  '/oauth2_callback': typeof Oauth2_callbackRoute
  '/$moduleId': typeof AppModuleIdRouteWithChildren
  '/documents': typeof AppDocumentsRoute
  '/settings': typeof AppSettingsRoute
  '/xcustomers': typeof AppXcustomersRouteWithChildren
  '/$moduleId/$table_name': typeof AppModuleIdTable_nameRouteWithChildren
  '/crm/home': typeof AppCrmHomeRouteWithChildren
  '/xcustomers/$id': typeof AppXcustomersIdRouteWithChildren
  '/xcustomers/new': typeof AppXcustomersNewRoute
  '/$moduleId/': typeof AppModuleIdIndexRoute
  '/$moduleId/$table_name/$key': typeof AppModuleIdTable_nameKeyRouteWithChildren
  '/crm/home/detail': typeof AppCrmHomeDetailRoute
  '/xcustomers/$id/edit': typeof AppXcustomersIdEditRoute
  '/$moduleId/$table_name/$key/view': typeof AppModuleIdTable_nameKeyViewRoute
}
export interface FileRoutesByTo {
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logout-success': typeof LogoutSuccessRoute
  '/oauth2_callback': typeof Oauth2_callbackRoute
  '/documents': typeof AppDocumentsRoute
  '/settings': typeof AppSettingsRoute
  '/xcustomers': typeof AppXcustomersRouteWithChildren
  '/': typeof AppIndexRoute
  '/$moduleId/$table_name': typeof AppModuleIdTable_nameRouteWithChildren
  '/crm/home': typeof AppCrmHomeRouteWithChildren
  '/xcustomers/$id': typeof AppXcustomersIdRouteWithChildren
  '/xcustomers/new': typeof AppXcustomersNewRoute
  '/$moduleId': typeof AppModuleIdIndexRoute
  '/$moduleId/$table_name/$key': typeof AppModuleIdTable_nameKeyRouteWithChildren
  '/crm/home/detail': typeof AppCrmHomeDetailRoute
  '/xcustomers/$id/edit': typeof AppXcustomersIdEditRoute
  '/$moduleId/$table_name/$key/view': typeof AppModuleIdTable_nameKeyViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/form-playground': typeof FormPlaygroundRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/logout-success': typeof LogoutSuccessRoute
  '/oauth2_callback': typeof Oauth2_callbackRoute
  '/_app/$moduleId': typeof AppModuleIdRouteWithChildren
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/xcustomers': typeof AppXcustomersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$moduleId/$table_name': typeof AppModuleIdTable_nameRouteWithChildren
  '/_app/crm/home': typeof AppCrmHomeRouteWithChildren
  '/_app/xcustomers/$id': typeof AppXcustomersIdRouteWithChildren
  '/_app/xcustomers/new': typeof AppXcustomersNewRoute
  '/_app/$moduleId/': typeof AppModuleIdIndexRoute
  '/_app/$moduleId/$table_name/$key': typeof AppModuleIdTable_nameKeyRouteWithChildren
  '/_app/crm/home/detail': typeof AppCrmHomeDetailRoute
  '/_app/xcustomers/$id/edit': typeof AppXcustomersIdEditRoute
  '/_app/$moduleId/$table_name/$key/view': typeof AppModuleIdTable_nameKeyViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form-playground'
    | '/login'
    | '/logout'
    | '/logout-success'
    | '/oauth2_callback'
    | '/$moduleId'
    | '/documents'
    | '/settings'
    | '/xcustomers'
    | '/$moduleId/$table_name'
    | '/crm/home'
    | '/xcustomers/$id'
    | '/xcustomers/new'
    | '/$moduleId/'
    | '/$moduleId/$table_name/$key'
    | '/crm/home/detail'
    | '/xcustomers/$id/edit'
    | '/$moduleId/$table_name/$key/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/form-playground'
    | '/login'
    | '/logout'
    | '/logout-success'
    | '/oauth2_callback'
    | '/documents'
    | '/settings'
    | '/xcustomers'
    | '/'
    | '/$moduleId/$table_name'
    | '/crm/home'
    | '/xcustomers/$id'
    | '/xcustomers/new'
    | '/$moduleId'
    | '/$moduleId/$table_name/$key'
    | '/crm/home/detail'
    | '/xcustomers/$id/edit'
    | '/$moduleId/$table_name/$key/view'
  id:
    | '__root__'
    | '/_app'
    | '/form-playground'
    | '/login'
    | '/logout'
    | '/logout-success'
    | '/oauth2_callback'
    | '/_app/$moduleId'
    | '/_app/documents'
    | '/_app/settings'
    | '/_app/xcustomers'
    | '/_app/'
    | '/_app/$moduleId/$table_name'
    | '/_app/crm/home'
    | '/_app/xcustomers/$id'
    | '/_app/xcustomers/new'
    | '/_app/$moduleId/'
    | '/_app/$moduleId/$table_name/$key'
    | '/_app/crm/home/detail'
    | '/_app/xcustomers/$id/edit'
    | '/_app/$moduleId/$table_name/$key/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  FormPlaygroundRoute: typeof FormPlaygroundRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  LogoutSuccessRoute: typeof LogoutSuccessRoute
  Oauth2_callbackRoute: typeof Oauth2_callbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-playground': {
      id: '/form-playground'
      path: '/form-playground'
      fullPath: '/form-playground'
      preLoaderRoute: typeof FormPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout-success': {
      id: '/logout-success'
      path: '/logout-success'
      fullPath: '/logout-success'
      preLoaderRoute: typeof LogoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2_callback': {
      id: '/oauth2_callback'
      path: '/oauth2_callback'
      fullPath: '/oauth2_callback'
      preLoaderRoute: typeof Oauth2_callbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$moduleId': {
      id: '/_app/$moduleId'
      path: '/$moduleId'
      fullPath: '/$moduleId'
      preLoaderRoute: typeof AppModuleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/xcustomers': {
      id: '/_app/xcustomers'
      path: '/xcustomers'
      fullPath: '/xcustomers'
      preLoaderRoute: typeof AppXcustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$moduleId/': {
      id: '/_app/$moduleId/'
      path: '/'
      fullPath: '/$moduleId/'
      preLoaderRoute: typeof AppModuleIdIndexRouteImport
      parentRoute: typeof AppModuleIdRoute
    }
    '/_app/$moduleId/$table_name': {
      id: '/_app/$moduleId/$table_name'
      path: '/$table_name'
      fullPath: '/$moduleId/$table_name'
      preLoaderRoute: typeof AppModuleIdTable_nameRouteImport
      parentRoute: typeof AppModuleIdRoute
    }
    '/_app/crm/home': {
      id: '/_app/crm/home'
      path: '/crm/home'
      fullPath: '/crm/home'
      preLoaderRoute: typeof AppCrmHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/xcustomers/$id': {
      id: '/_app/xcustomers/$id'
      path: '/$id'
      fullPath: '/xcustomers/$id'
      preLoaderRoute: typeof AppXcustomersIdRouteImport
      parentRoute: typeof AppXcustomersRoute
    }
    '/_app/xcustomers/new': {
      id: '/_app/xcustomers/new'
      path: '/new'
      fullPath: '/xcustomers/new'
      preLoaderRoute: typeof AppXcustomersNewRouteImport
      parentRoute: typeof AppXcustomersRoute
    }
    '/_app/$moduleId/$table_name/$key': {
      id: '/_app/$moduleId/$table_name/$key'
      path: '/$key'
      fullPath: '/$moduleId/$table_name/$key'
      preLoaderRoute: typeof AppModuleIdTable_nameKeyRouteImport
      parentRoute: typeof AppModuleIdTable_nameRoute
    }
    '/_app/crm/home/detail': {
      id: '/_app/crm/home/detail'
      path: '/detail'
      fullPath: '/crm/home/detail'
      preLoaderRoute: typeof AppCrmHomeDetailRouteImport
      parentRoute: typeof AppCrmHomeRoute
    }
    '/_app/xcustomers/$id/edit': {
      id: '/_app/xcustomers/$id/edit'
      path: '/edit'
      fullPath: '/xcustomers/$id/edit'
      preLoaderRoute: typeof AppXcustomersIdEditRouteImport
      parentRoute: typeof AppXcustomersIdRoute
    }
    '/_app/$moduleId/$table_name/$key/view': {
      id: '/_app/$moduleId/$table_name/$key/view'
      path: '/view'
      fullPath: '/$moduleId/$table_name/$key/view'
      preLoaderRoute: typeof AppModuleIdTable_nameKeyViewRouteImport
      parentRoute: typeof AppModuleIdTable_nameKeyRoute
    }
  }
}

interface AppModuleIdTable_nameKeyRouteChildren {
  AppModuleIdTable_nameKeyViewRoute: typeof AppModuleIdTable_nameKeyViewRoute
}

const AppModuleIdTable_nameKeyRouteChildren: AppModuleIdTable_nameKeyRouteChildren =
  {
    AppModuleIdTable_nameKeyViewRoute: AppModuleIdTable_nameKeyViewRoute,
  }

const AppModuleIdTable_nameKeyRouteWithChildren =
  AppModuleIdTable_nameKeyRoute._addFileChildren(
    AppModuleIdTable_nameKeyRouteChildren,
  )

interface AppModuleIdTable_nameRouteChildren {
  AppModuleIdTable_nameKeyRoute: typeof AppModuleIdTable_nameKeyRouteWithChildren
}

const AppModuleIdTable_nameRouteChildren: AppModuleIdTable_nameRouteChildren = {
  AppModuleIdTable_nameKeyRoute: AppModuleIdTable_nameKeyRouteWithChildren,
}

const AppModuleIdTable_nameRouteWithChildren =
  AppModuleIdTable_nameRoute._addFileChildren(
    AppModuleIdTable_nameRouteChildren,
  )

interface AppModuleIdRouteChildren {
  AppModuleIdTable_nameRoute: typeof AppModuleIdTable_nameRouteWithChildren
  AppModuleIdIndexRoute: typeof AppModuleIdIndexRoute
}

const AppModuleIdRouteChildren: AppModuleIdRouteChildren = {
  AppModuleIdTable_nameRoute: AppModuleIdTable_nameRouteWithChildren,
  AppModuleIdIndexRoute: AppModuleIdIndexRoute,
}

const AppModuleIdRouteWithChildren = AppModuleIdRoute._addFileChildren(
  AppModuleIdRouteChildren,
)

interface AppXcustomersIdRouteChildren {
  AppXcustomersIdEditRoute: typeof AppXcustomersIdEditRoute
}

const AppXcustomersIdRouteChildren: AppXcustomersIdRouteChildren = {
  AppXcustomersIdEditRoute: AppXcustomersIdEditRoute,
}

const AppXcustomersIdRouteWithChildren = AppXcustomersIdRoute._addFileChildren(
  AppXcustomersIdRouteChildren,
)

interface AppXcustomersRouteChildren {
  AppXcustomersIdRoute: typeof AppXcustomersIdRouteWithChildren
  AppXcustomersNewRoute: typeof AppXcustomersNewRoute
}

const AppXcustomersRouteChildren: AppXcustomersRouteChildren = {
  AppXcustomersIdRoute: AppXcustomersIdRouteWithChildren,
  AppXcustomersNewRoute: AppXcustomersNewRoute,
}

const AppXcustomersRouteWithChildren = AppXcustomersRoute._addFileChildren(
  AppXcustomersRouteChildren,
)

interface AppCrmHomeRouteChildren {
  AppCrmHomeDetailRoute: typeof AppCrmHomeDetailRoute
}

const AppCrmHomeRouteChildren: AppCrmHomeRouteChildren = {
  AppCrmHomeDetailRoute: AppCrmHomeDetailRoute,
}

const AppCrmHomeRouteWithChildren = AppCrmHomeRoute._addFileChildren(
  AppCrmHomeRouteChildren,
)

interface AppRouteChildren {
  AppModuleIdRoute: typeof AppModuleIdRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppXcustomersRoute: typeof AppXcustomersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCrmHomeRoute: typeof AppCrmHomeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleIdRoute: AppModuleIdRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppXcustomersRoute: AppXcustomersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCrmHomeRoute: AppCrmHomeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  FormPlaygroundRoute: FormPlaygroundRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  LogoutSuccessRoute: LogoutSuccessRoute,
  Oauth2_callbackRoute: Oauth2_callbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
